### ISSUE TITLE
limit manifest size

### ISSUE THREAD

**Issue by strantalis** [opentdf/java-sdk#155]
In the go sdk it was detected that a protocol attack could happen by reading an excessively large manifest. We should introduce the same limits within the java-sdk.

Let's do a test that recreates the test done on the Go sdk, using a tdf with a large manifest, and observe the behavior in order to determine what is needed for this ticket. 

REF: https://github.com/opentdf/platform/pull/1385

Acceptance Criteria:
- Test to make sure a manifest isn't larger than 10mb

**Comment by mkleene** [comment]
I don't think we have this _exact_ vulnerability since all of our reads are in terms of segments but we seemingly have a related one where [we allocate a buffer based on a stated segment size](https://github.com/opentdf/java-sdk/blob/main/sdk/src/main/java/io/opentdf/platform/sdk/TDF.java#L324).

The simplest fix for this is likely to fix a maximum (ideally encrypted) segment size. [One doesn't currently appear to exist](https://github.com/opentdf/spec/blob/main/schema/tdf/Manifest.md#encryptioninformationintegrityinformationsegment) but it might be a good idea to add one, I think.

@strantalis

**Comment by strantalis** [comment]
> I don't think we have this _exact_ vulnerability since all of our reads are in terms of segments but we seemingly have a related one where [we allocate a buffer based on a stated segment size](https://github.com/opentdf/java-sdk/blob/main/sdk/src/main/java/io/opentdf/platform/sdk/TDF.java#L324).
> 
> The simplest fix for this is likely to fix a maximum (ideally encrypted) segment size. [One doesn't currently appear to exist](https://github.com/opentdf/spec/blob/main/schema/tdf/Manifest.md#encryptioninformationintegrityinformationsegment) but it might be a good idea to add one, I think.
> 
> @strantalis

@mkleene This has to do more with the manifest size. I don't think we restrict that right?

**Comment by mkleene** [comment]
@strantalis that makes sense; I guess that if someone gives us a big TDF then it will make us consume large amounts of memory and that is still bad. I was referring to the protocol aspect where you could have a tiny TDF that advertises a large manifest and forces you to use memory. We should still restrict the size of the manifest to protect against clients that submit large TDFs but the attached test cases don't apply.

**Comment by sujankota** [comment]
https://github.com/opentdf/java-sdk/pull/167
